### ISSUE TITLE
Qualitative Data

### ISSUE THREAD

**Issue by cyouh95** [mabrown1/intro-data-capstone-musclehub#4]
It'd be great if you could also include some observations/analysis on the interview data provided in the project.

**Comment by mabrown1** [comment]
Do I need to resubmit?

mabrown1

**Comment by cyouh95** [comment]
No, these are just some suggestions. Great job again on this, and congratulations for finishing the course!

**Comment by mabrown1** [comment]
Thank you.  Great course.
